
spring.datasource.url=jdbc:postgresql://localhost:5442/lordship_test
spring.datasource.username=test_db_admin
spring.datasource.password=admin123

jwt.secret=EYThLdz3cykdbT7fz2h3jokPErNVKXYhuomRRZMolQz
jwt.expiration-ms=86400000

lordship.root.email=root@lordship.com
lordship.root.password=rooto123

lordship.encryption.algorithm=AES/GCM/NoPadding
lordship.encryption.keys=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=